### PR TITLE
Added friendly_id to maps

### PR DESCRIPTION
**Pull request by vpowerrc**
In old mapknitter, it used "name" as unique field. But now we use "slug" or "id" field for that.
So I changed most of the href links which refers to a map by its name, to slug field. 
I skipped changing them in legacy map views because they don't work anymore.
Also, I didn't change them in image, export and tms links because it could effect the current data. 
We need to fix them too.

### CODE REVIEW

**Comment by jywarren** [comment]
OK, i've successfully merged this into the v2-intial-release branch, and then into publiclab master! Thanks, @vpowerrc!

**Comment by jywarren** [comment]
Hi, @vpowerrc, I'm getting

    Mysql2::Error: Duplicate entry 'njn' for key 'index_maps_on_slug': UPDATE maps m SET m.slug = m.name

when I run it on a copy of the production database. Perhaps we have to insert a line to find and delete duplicate map names, or something? I'll manually fix that and see if it's the only one.

**Comment by jywarren** [comment]
none I've found include two copies of a map where both have images. So I'm writing a part of the migration to delete image-less map duplicates; we'll see how that goes.

**Comment by vpowerrc** [comment]
Okay. BTW did you see my comment above? I didn't change some of the links/routes. We have to change them, otherwise app won't work properly. Please check it

**Comment by jywarren** [comment]
yes, thanks. I'll be overhauling all of the routes, and preserving all legacy URLs

**Comment by vpowerrc** [comment]
cool

**Pull request closed without merging**
